### ISSUE TITLE
Use 'master' instead of 'main'?

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-node-client#2]
Hi @jeff-zucker,
Would it be OK to rename the 'main' branch to 'master', for consistency?

Cheers,
Michiel

**Comment by jeff-zucker** [comment]
Done, thanks

**Comment by jeff-zucker** [comment]
Hmm, I just checked on github and now understand what happened here.  It may be something to consider for all our libraries, though it would be a pain.  Basically, github, like many tech companies, out of respect for the Black Lives Matter movement, is eliminating all language that uses the "master/slave" analogy.  So github's default branch is now called main by default.

**Comment by jeff-zucker** [comment]
I don't know how this will impact your scripts but check this out : https://github.com/github/renaming.  Among other things it says "We've updated GitHub.com to redirect links that contain the deleted branch name master to the corresponding link in the repository's new default branch."

**Comment by bourgeoa** [comment]
It also say don't rename now and wait `later` ...

**Comment by jeff-zucker** [comment]
Yes it does, so I am leaving main as the default for the time being.

**Comment by michielbdejong** [comment]
Thanks for looking into this!

https://gitter.im/solid/solidos?at=5f9fe160c6fe0131d4cdd98e
