### ISSUE TITLE
one-liner to reset a folder on pod to a local folder?

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-node-client#8]
I have uploaded some files to my pod.
Now I fixed some things in the local copy and want to sync those changes to my pod.
I use the local copy as authoritative so it's OK to delete the folder contents on my pod and
upload from scratch.

I'll see if I can produce a script for that.

**Comment by jeff-zucker** [comment]
One-liner recursive copy, backup, and restore is now handled by [solid-shell](https://github.com/jeff-zucker/solid-shell)  which uses solid-node-client and solid-file-client: 
 ```
sol copy local_folder remote_folder
```
or 
```
sol zip folderUrl zipFile
```
